---
label: Package
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: discount
  type: number
  label: Discount
  description: Value is for %
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: most_popular
  type: boolean
  label: Most Popular
  description: Only one package should have this set
- name: services
  type: field_group_list
  fields:
  - name: service
    type: include
    config: {}
    template: service
    label: Service
  config:
    min: 
    max: 
    labelField: 
  label: Services
