---
label: Package
hide_body: true
fields:
- name: package_name
  type: text
  config:
    required: false
  label: Name
- name: package_discount
  type: number
  label: Discount
  description: Value is for %
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: most_popular
  type: boolean
  label: Most Popular
  description: Only one package should have this set
- name: package_services
  type: field_group_list
  fields:
  - name: service
    type: select
    default: []
    config:
      required: false
      options: []
      source:
        type: pages
        section: services-65f6fe1a-d521-41f2-a7d4-b47a2f7e0de7
        file: 
        path: 
    label: Service
  config:
    min: 
    max: 
    labelField: service
  label: Services
- name: key
  type: text
  config:
    required: false
  label: key
  default: package
  hidden: true
pages:
- content/packages/full-coverage.md
- content/packages/matterport_hdr-photos.md
- content/packages/property-showcase.md
