---
label: Service
hide_body: true
fields:
- name: name
  type: text
  config:
    required: true
  label: Name
- name: price
  type: field_group
  config: {}
  fields:
  - name: condo
    type: number
    label: Condo
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
      required: false
  - name: house
    type: number
    label: House
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
      required: false
  label: Price
- name: description
  type: field_group
  config: {}
  fields:
  - name: condo
    type: text
    config:
      required: false
    label: Condo
  - name: house
    type: text
    config:
      required: false
    label: House
  label: Description
- name: disclaimer
  type: text
  config:
    required: false
  label: Disclaimer
- name: multiple
  type: boolean
  label: Multiple
  description: Turn on when the user can get multiples of the service.
- name: package_only
  type: boolean
  label: Package Only
  description: Only show this service in a package and not in the 'A la cart' section
pages:
- content/services/24-hour-rush-fee.md
- content/services/extra-hdr-aerial-photo.md
- content/services/extra-hdr-property-photos.md
- content/services/hdr-aerial-photos.md
- content/services/hdr-drone-video.md
- content/services/hdr-interior-video.md
- content/services/hdr-property-photos.md
- content/services/matterport-storage.md
- content/services/virtual-tour.md
