---
label: Service
hide_body: true
fields:
- name: service_name
  type: text
  config:
    required: true
  label: Name
- name: service_price
  type: field_group
  config: {}
  fields:
  - name: condo
    type: number
    label: Condo
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
      required: false
  - name: house
    type: number
    label: House
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
      required: false
  label: Price
- name: service_description
  type: field_group
  config: {}
  fields:
  - name: condo
    type: text
    config:
      required: false
    label: Condo
  - name: house
    type: text
    config:
      required: false
    label: House
  label: Description
- name: service_disclaimer
  type: text
  config:
    required: false
  label: Disclaimer
- name: service_multiple
  type: boolean
  label: Multiple
  description: Turn on when the user can get multiples of the service.
- name: service_package_only
  type: boolean
  label: Package Only
  description: Only show this service in a package and not in the 'A la cart' section
- name: key
  type: text
  config:
    required: false
  label: key
  hidden: true
  default: service
pages:
- content/services/24-hour-rush-fee.md
- content/services/extra-hdr-aerial-photo.md
- content/services/extra-hdr-property-photos.md
- content/services/floor-plan.md
- content/services/hdr-aerial-photos.md
- content/services/hdr-drone-video.md
- content/services/hdr-interior-video.md
- content/services/hdr-property-photos.md
- content/services/matterport-storage.md
- content/services/planning-and-coordination.md
- content/services/video-editing.md
- content/services/virtual-tour.md
