---
label: Service
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: price
  type: field_group
  config: {}
  fields:
  - name: condo
    type: number
    label: Condo
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
  - name: house
    type: number
    label: House
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
  label: Price
- name: description
  type: field_group
  config: {}
  fields:
  - name: condo
    type: text
    config:
      required: false
    label: Condo
  - name: house
    type: text
    config:
      required: false
    label: House
  label: Description
