---
label: Service
hide_body: true
fields:
- name: name
  type: text
  config:
    required: true
  label: Name
  description: Name of the service
- name: price
  type: number
  label: Price
  description: Price of service
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: class
  type: select
  default: []
  config:
    required: false
    options:
    - Condo
    - House
    source:
      type: simple
      section: classes
      file: 
      path: 
  label: Class
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - Photo
    - 3D Virtual Tour
    - Video
    - Extra
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
